version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-networks
    volumes:
      - ./node:/usr/src/app
    tty: true
    command: "npm run dev"
    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "81:80"
    networks:
      - node-networks

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - node-networks

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-networks

networks:
  node-networks:
    driver: bridge
